"""Report generation: CSV and PDF exports.

Only aggregates the caller is already authorised to see should be passed in -
the routers build the data, this module only formats it.
"""

from __future__ import annotations

import csv
import io
from typing import Any, Dict, List, Optional


def build_csv(rows: List[Dict[str, Any]], columns: Optional[List[str]] = None) -> bytes:
    if not rows:
        return b""
    cols = columns or list(rows[0].keys())
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(cols)
    for row in rows:
        writer.writerow([_csv_cell(row.get(c)) for c in cols])
    return buf.getvalue().encode("utf-8")


def _csv_cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (list, dict)):
        return str(value)
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return str(value)


def build_pdf(
    title: str,
    subtitle: Optional[str],
    sections: List[Dict[str, Any]],
) -> bytes:
    """Render a simple PDF report.

    Each section is {"heading": str, "columns": [str], "rows": [[v,...]]} or
    {"heading": str, "paragraphs": [str]}.
    """
    from fpdf import FPDF

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, _safe_pdf_text(title), ln=True)
    if subtitle:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(90, 90, 90)
        pdf.cell(0, 6, _safe_pdf_text(subtitle), ln=True)
        pdf.set_text_color(0, 0, 0)
    pdf.ln(4)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    for section in sections:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, _safe_pdf_text(section.get("heading", "")), ln=True)
        pdf.ln(1)

        if section.get("paragraphs"):
            pdf.set_font("Helvetica", "", 10)
            for p in section["paragraphs"]:
                pdf.multi_cell(0, 5, _safe_pdf_text(p))
            pdf.ln(2)

        cols = section.get("columns")
        rows = section.get("rows")
        if cols and rows is not None:
            if not rows:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(120, 120, 120)
                pdf.cell(0, 6, "No records.", ln=True)
                pdf.set_text_color(0, 0, 0)
            else:
                usable = 190
                col_w = usable / len(cols)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_fill_color(235, 238, 243)
                for c in cols:
                    pdf.cell(col_w, 7, _safe_pdf_text(c), border=1, fill=True)
                pdf.ln()
                pdf.set_font("Helvetica", "", 9)
                for row in rows:
                    for c in row:
                        pdf.cell(col_w, 6, _safe_pdf_text(c), border=1)
                    pdf.ln()
            pdf.ln(4)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.cell(0, 5, "Generated by CampusIQ - Smart College Management Platform", ln=True)
    return bytes(pdf.output())


def _safe_pdf_text(value: Any) -> str:
    """fpdf2 with core fonts is latin-1; strip anything outside it."""
    text = "" if value is None else str(value)
    try:
        return text.encode("latin-1", "replace").decode("latin-1")
    except Exception:
        return "".join(c if ord(c) < 256 else "?" for c in text)
